// Generated by gencpp from file jwaad_test/FaceLockOnResult.msg
// DO NOT EDIT!


#ifndef JWAAD_TEST_MESSAGE_FACELOCKONRESULT_H
#define JWAAD_TEST_MESSAGE_FACELOCKONRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jwaad_test
{
template <class ContainerAllocator>
struct FaceLockOnResult_
{
  typedef FaceLockOnResult_<ContainerAllocator> Type;

  FaceLockOnResult_()
    : completed(false)  {
    }
  FaceLockOnResult_(const ContainerAllocator& _alloc)
    : completed(false)  {
  (void)_alloc;
    }



   typedef uint8_t _completed_type;
  _completed_type completed;





  typedef boost::shared_ptr< ::jwaad_test::FaceLockOnResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jwaad_test::FaceLockOnResult_<ContainerAllocator> const> ConstPtr;

}; // struct FaceLockOnResult_

typedef ::jwaad_test::FaceLockOnResult_<std::allocator<void> > FaceLockOnResult;

typedef boost::shared_ptr< ::jwaad_test::FaceLockOnResult > FaceLockOnResultPtr;
typedef boost::shared_ptr< ::jwaad_test::FaceLockOnResult const> FaceLockOnResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jwaad_test::FaceLockOnResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jwaad_test::FaceLockOnResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jwaad_test::FaceLockOnResult_<ContainerAllocator1> & lhs, const ::jwaad_test::FaceLockOnResult_<ContainerAllocator2> & rhs)
{
  return lhs.completed == rhs.completed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jwaad_test::FaceLockOnResult_<ContainerAllocator1> & lhs, const ::jwaad_test::FaceLockOnResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jwaad_test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::jwaad_test::FaceLockOnResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jwaad_test::FaceLockOnResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jwaad_test::FaceLockOnResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jwaad_test::FaceLockOnResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jwaad_test::FaceLockOnResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jwaad_test::FaceLockOnResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jwaad_test::FaceLockOnResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9e58faa17a4877a1efc0e251b503c53b";
  }

  static const char* value(const ::jwaad_test::FaceLockOnResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9e58faa17a4877a1ULL;
  static const uint64_t static_value2 = 0xefc0e251b503c53bULL;
};

template<class ContainerAllocator>
struct DataType< ::jwaad_test::FaceLockOnResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jwaad_test/FaceLockOnResult";
  }

  static const char* value(const ::jwaad_test::FaceLockOnResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jwaad_test::FaceLockOnResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"bool completed\n"
;
  }

  static const char* value(const ::jwaad_test::FaceLockOnResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jwaad_test::FaceLockOnResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.completed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FaceLockOnResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jwaad_test::FaceLockOnResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jwaad_test::FaceLockOnResult_<ContainerAllocator>& v)
  {
    s << indent << "completed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.completed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JWAAD_TEST_MESSAGE_FACELOCKONRESULT_H
