// Generated by gencpp from file jwaad_test/FaceLockOnGoal.msg
// DO NOT EDIT!


#ifndef JWAAD_TEST_MESSAGE_FACELOCKONGOAL_H
#define JWAAD_TEST_MESSAGE_FACELOCKONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace jwaad_test
{
template <class ContainerAllocator>
struct FaceLockOnGoal_
{
  typedef FaceLockOnGoal_<ContainerAllocator> Type;

  FaceLockOnGoal_()
    : y_offset(0)
    , x_offset(0)  {
    }
  FaceLockOnGoal_(const ContainerAllocator& _alloc)
    : y_offset(0)
    , x_offset(0)  {
  (void)_alloc;
    }



   typedef int16_t _y_offset_type;
  _y_offset_type y_offset;

   typedef int16_t _x_offset_type;
  _x_offset_type x_offset;





  typedef boost::shared_ptr< ::jwaad_test::FaceLockOnGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jwaad_test::FaceLockOnGoal_<ContainerAllocator> const> ConstPtr;

}; // struct FaceLockOnGoal_

typedef ::jwaad_test::FaceLockOnGoal_<std::allocator<void> > FaceLockOnGoal;

typedef boost::shared_ptr< ::jwaad_test::FaceLockOnGoal > FaceLockOnGoalPtr;
typedef boost::shared_ptr< ::jwaad_test::FaceLockOnGoal const> FaceLockOnGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jwaad_test::FaceLockOnGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jwaad_test::FaceLockOnGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jwaad_test::FaceLockOnGoal_<ContainerAllocator1> & lhs, const ::jwaad_test::FaceLockOnGoal_<ContainerAllocator2> & rhs)
{
  return lhs.y_offset == rhs.y_offset &&
    lhs.x_offset == rhs.x_offset;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jwaad_test::FaceLockOnGoal_<ContainerAllocator1> & lhs, const ::jwaad_test::FaceLockOnGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jwaad_test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::jwaad_test::FaceLockOnGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jwaad_test::FaceLockOnGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jwaad_test::FaceLockOnGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jwaad_test::FaceLockOnGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jwaad_test::FaceLockOnGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jwaad_test::FaceLockOnGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jwaad_test::FaceLockOnGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0b4343f973d79e4f2bb90d257f10526b";
  }

  static const char* value(const ::jwaad_test::FaceLockOnGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0b4343f973d79e4fULL;
  static const uint64_t static_value2 = 0x2bb90d257f10526bULL;
};

template<class ContainerAllocator>
struct DataType< ::jwaad_test::FaceLockOnGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jwaad_test/FaceLockOnGoal";
  }

  static const char* value(const ::jwaad_test::FaceLockOnGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jwaad_test::FaceLockOnGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"int16 y_offset\n"
"int16 x_offset\n"
;
  }

  static const char* value(const ::jwaad_test::FaceLockOnGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jwaad_test::FaceLockOnGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.y_offset);
      stream.next(m.x_offset);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FaceLockOnGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jwaad_test::FaceLockOnGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jwaad_test::FaceLockOnGoal_<ContainerAllocator>& v)
  {
    s << indent << "y_offset: ";
    Printer<int16_t>::stream(s, indent + "  ", v.y_offset);
    s << indent << "x_offset: ";
    Printer<int16_t>::stream(s, indent + "  ", v.x_offset);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JWAAD_TEST_MESSAGE_FACELOCKONGOAL_H
