(cl:defpackage jwaad_test-msg
  (:use )
  (:export
   "<FACELOCKONACTION>"
   "FACELOCKONACTION"
   "<FACELOCKONACTIONFEEDBACK>"
   "FACELOCKONACTIONFEEDBACK"
   "<FACELOCKONACTIONGOAL>"
   "FACELOCKONACTIONGOAL"
   "<FACELOCKONACTIONRESULT>"
   "FACELOCKONACTIONRESULT"
   "<FACELOCKONFEEDBACK>"
   "FACELOCKONFEEDBACK"
   "<FACELOCKONGOAL>"
   "FACELOCKONGOAL"
   "<FACELOCKONRESULT>"
   "FACELOCKONRESULT"
  ))

