; Auto-generated. Do not edit!


(cl:in-package jwaad_test-msg)


;//! \htmlinclude FaceLockOnResult.msg.html

(cl:defclass <FaceLockOnResult> (roslisp-msg-protocol:ros-message)
  ((completed
    :reader completed
    :initarg :completed
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass FaceLockOnResult (<FaceLockOnResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FaceLockOnResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FaceLockOnResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name jwaad_test-msg:<FaceLockOnResult> is deprecated: use jwaad_test-msg:FaceLockOnResult instead.")))

(cl:ensure-generic-function 'completed-val :lambda-list '(m))
(cl:defmethod completed-val ((m <FaceLockOnResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader jwaad_test-msg:completed-val is deprecated.  Use jwaad_test-msg:completed instead.")
  (completed m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FaceLockOnResult>) ostream)
  "Serializes a message object of type '<FaceLockOnResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'completed) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FaceLockOnResult>) istream)
  "Deserializes a message object of type '<FaceLockOnResult>"
    (cl:setf (cl:slot-value msg 'completed) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FaceLockOnResult>)))
  "Returns string type for a message object of type '<FaceLockOnResult>"
  "jwaad_test/FaceLockOnResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FaceLockOnResult)))
  "Returns string type for a message object of type 'FaceLockOnResult"
  "jwaad_test/FaceLockOnResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FaceLockOnResult>)))
  "Returns md5sum for a message object of type '<FaceLockOnResult>"
  "9e58faa17a4877a1efc0e251b503c53b")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FaceLockOnResult)))
  "Returns md5sum for a message object of type 'FaceLockOnResult"
  "9e58faa17a4877a1efc0e251b503c53b")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FaceLockOnResult>)))
  "Returns full string definition for message of type '<FaceLockOnResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool completed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FaceLockOnResult)))
  "Returns full string definition for message of type 'FaceLockOnResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool completed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FaceLockOnResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FaceLockOnResult>))
  "Converts a ROS message object to a list"
  (cl:list 'FaceLockOnResult
    (cl:cons ':completed (completed msg))
))
