; Auto-generated. Do not edit!


(cl:in-package jwaad_test-msg)


;//! \htmlinclude FaceLockOnGoal.msg.html

(cl:defclass <FaceLockOnGoal> (roslisp-msg-protocol:ros-message)
  ((y_offset
    :reader y_offset
    :initarg :y_offset
    :type cl:fixnum
    :initform 0)
   (x_offset
    :reader x_offset
    :initarg :x_offset
    :type cl:fixnum
    :initform 0))
)

(cl:defclass FaceLockOnGoal (<FaceLockOnGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FaceLockOnGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FaceLockOnGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name jwaad_test-msg:<FaceLockOnGoal> is deprecated: use jwaad_test-msg:FaceLockOnGoal instead.")))

(cl:ensure-generic-function 'y_offset-val :lambda-list '(m))
(cl:defmethod y_offset-val ((m <FaceLockOnGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader jwaad_test-msg:y_offset-val is deprecated.  Use jwaad_test-msg:y_offset instead.")
  (y_offset m))

(cl:ensure-generic-function 'x_offset-val :lambda-list '(m))
(cl:defmethod x_offset-val ((m <FaceLockOnGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader jwaad_test-msg:x_offset-val is deprecated.  Use jwaad_test-msg:x_offset instead.")
  (x_offset m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FaceLockOnGoal>) ostream)
  "Serializes a message object of type '<FaceLockOnGoal>"
  (cl:let* ((signed (cl:slot-value msg 'y_offset)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 65536) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    )
  (cl:let* ((signed (cl:slot-value msg 'x_offset)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 65536) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FaceLockOnGoal>) istream)
  "Deserializes a message object of type '<FaceLockOnGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'y_offset) (cl:if (cl:< unsigned 32768) unsigned (cl:- unsigned 65536))))
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'x_offset) (cl:if (cl:< unsigned 32768) unsigned (cl:- unsigned 65536))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FaceLockOnGoal>)))
  "Returns string type for a message object of type '<FaceLockOnGoal>"
  "jwaad_test/FaceLockOnGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FaceLockOnGoal)))
  "Returns string type for a message object of type 'FaceLockOnGoal"
  "jwaad_test/FaceLockOnGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FaceLockOnGoal>)))
  "Returns md5sum for a message object of type '<FaceLockOnGoal>"
  "0b4343f973d79e4f2bb90d257f10526b")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FaceLockOnGoal)))
  "Returns md5sum for a message object of type 'FaceLockOnGoal"
  "0b4343f973d79e4f2bb90d257f10526b")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FaceLockOnGoal>)))
  "Returns full string definition for message of type '<FaceLockOnGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int16 y_offset~%int16 x_offset~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FaceLockOnGoal)))
  "Returns full string definition for message of type 'FaceLockOnGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int16 y_offset~%int16 x_offset~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FaceLockOnGoal>))
  (cl:+ 0
     2
     2
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FaceLockOnGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'FaceLockOnGoal
    (cl:cons ':y_offset (y_offset msg))
    (cl:cons ':x_offset (x_offset msg))
))
