; Auto-generated. Do not edit!


(cl:in-package jwaad_test-msg)


;//! \htmlinclude FaceLockOnFeedback.msg.html

(cl:defclass <FaceLockOnFeedback> (roslisp-msg-protocol:ros-message)
  ((remaining_y_offset
    :reader remaining_y_offset
    :initarg :remaining_y_offset
    :type cl:fixnum
    :initform 0)
   (remaining_x_offset
    :reader remaining_x_offset
    :initarg :remaining_x_offset
    :type cl:fixnum
    :initform 0))
)

(cl:defclass FaceLockOnFeedback (<FaceLockOnFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FaceLockOnFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FaceLockOnFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name jwaad_test-msg:<FaceLockOnFeedback> is deprecated: use jwaad_test-msg:FaceLockOnFeedback instead.")))

(cl:ensure-generic-function 'remaining_y_offset-val :lambda-list '(m))
(cl:defmethod remaining_y_offset-val ((m <FaceLockOnFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader jwaad_test-msg:remaining_y_offset-val is deprecated.  Use jwaad_test-msg:remaining_y_offset instead.")
  (remaining_y_offset m))

(cl:ensure-generic-function 'remaining_x_offset-val :lambda-list '(m))
(cl:defmethod remaining_x_offset-val ((m <FaceLockOnFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader jwaad_test-msg:remaining_x_offset-val is deprecated.  Use jwaad_test-msg:remaining_x_offset instead.")
  (remaining_x_offset m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FaceLockOnFeedback>) ostream)
  "Serializes a message object of type '<FaceLockOnFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'remaining_y_offset)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 65536) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    )
  (cl:let* ((signed (cl:slot-value msg 'remaining_x_offset)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 65536) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FaceLockOnFeedback>) istream)
  "Deserializes a message object of type '<FaceLockOnFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'remaining_y_offset) (cl:if (cl:< unsigned 32768) unsigned (cl:- unsigned 65536))))
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'remaining_x_offset) (cl:if (cl:< unsigned 32768) unsigned (cl:- unsigned 65536))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FaceLockOnFeedback>)))
  "Returns string type for a message object of type '<FaceLockOnFeedback>"
  "jwaad_test/FaceLockOnFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FaceLockOnFeedback)))
  "Returns string type for a message object of type 'FaceLockOnFeedback"
  "jwaad_test/FaceLockOnFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FaceLockOnFeedback>)))
  "Returns md5sum for a message object of type '<FaceLockOnFeedback>"
  "f85529854f9db9feef1acea870997bcc")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FaceLockOnFeedback)))
  "Returns md5sum for a message object of type 'FaceLockOnFeedback"
  "f85529854f9db9feef1acea870997bcc")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FaceLockOnFeedback>)))
  "Returns full string definition for message of type '<FaceLockOnFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int16 remaining_y_offset~%int16 remaining_x_offset~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FaceLockOnFeedback)))
  "Returns full string definition for message of type 'FaceLockOnFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int16 remaining_y_offset~%int16 remaining_x_offset~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FaceLockOnFeedback>))
  (cl:+ 0
     2
     2
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FaceLockOnFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'FaceLockOnFeedback
    (cl:cons ':remaining_y_offset (remaining_y_offset msg))
    (cl:cons ':remaining_x_offset (remaining_x_offset msg))
))
