; Auto-generated. Do not edit!


(cl:in-package jwaad_test-msg)


;//! \htmlinclude face_lock_onGoal.msg.html

(cl:defclass <face_lock_onGoal> (roslisp-msg-protocol:ros-message)
  ((order
    :reader order
    :initarg :order
    :type cl:integer
    :initform 0))
)

(cl:defclass face_lock_onGoal (<face_lock_onGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <face_lock_onGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'face_lock_onGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name jwaad_test-msg:<face_lock_onGoal> is deprecated: use jwaad_test-msg:face_lock_onGoal instead.")))

(cl:ensure-generic-function 'order-val :lambda-list '(m))
(cl:defmethod order-val ((m <face_lock_onGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader jwaad_test-msg:order-val is deprecated.  Use jwaad_test-msg:order instead.")
  (order m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <face_lock_onGoal>) ostream)
  "Serializes a message object of type '<face_lock_onGoal>"
  (cl:let* ((signed (cl:slot-value msg 'order)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <face_lock_onGoal>) istream)
  "Deserializes a message object of type '<face_lock_onGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'order) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<face_lock_onGoal>)))
  "Returns string type for a message object of type '<face_lock_onGoal>"
  "jwaad_test/face_lock_onGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'face_lock_onGoal)))
  "Returns string type for a message object of type 'face_lock_onGoal"
  "jwaad_test/face_lock_onGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<face_lock_onGoal>)))
  "Returns md5sum for a message object of type '<face_lock_onGoal>"
  "6889063349a00b249bd1661df429d822")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'face_lock_onGoal)))
  "Returns md5sum for a message object of type 'face_lock_onGoal"
  "6889063349a00b249bd1661df429d822")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<face_lock_onGoal>)))
  "Returns full string definition for message of type '<face_lock_onGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int32 order~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'face_lock_onGoal)))
  "Returns full string definition for message of type 'face_lock_onGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int32 order~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <face_lock_onGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <face_lock_onGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'face_lock_onGoal
    (cl:cons ':order (order msg))
))
