// Generated by gencpp from file musi_care/qt_commandResponse.msg
// DO NOT EDIT!


#ifndef MUSI_CARE_MESSAGE_QT_COMMANDRESPONSE_H
#define MUSI_CARE_MESSAGE_QT_COMMANDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace musi_care
{
template <class ContainerAllocator>
struct qt_commandResponse_
{
  typedef qt_commandResponse_<ContainerAllocator> Type;

  qt_commandResponse_()
    : status(false)  {
    }
  qt_commandResponse_(const ContainerAllocator& _alloc)
    : status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::musi_care::qt_commandResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::musi_care::qt_commandResponse_<ContainerAllocator> const> ConstPtr;

}; // struct qt_commandResponse_

typedef ::musi_care::qt_commandResponse_<std::allocator<void> > qt_commandResponse;

typedef boost::shared_ptr< ::musi_care::qt_commandResponse > qt_commandResponsePtr;
typedef boost::shared_ptr< ::musi_care::qt_commandResponse const> qt_commandResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::musi_care::qt_commandResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::musi_care::qt_commandResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::musi_care::qt_commandResponse_<ContainerAllocator1> & lhs, const ::musi_care::qt_commandResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::musi_care::qt_commandResponse_<ContainerAllocator1> & lhs, const ::musi_care::qt_commandResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace musi_care

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::musi_care::qt_commandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::musi_care::qt_commandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::musi_care::qt_commandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::musi_care::qt_commandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::musi_care::qt_commandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::musi_care::qt_commandResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::musi_care::qt_commandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::musi_care::qt_commandResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1255d4d998bd4dULL;
  static const uint64_t static_value2 = 0x6585c64639b5ee9aULL;
};

template<class ContainerAllocator>
struct DataType< ::musi_care::qt_commandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "musi_care/qt_commandResponse";
  }

  static const char* value(const ::musi_care::qt_commandResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::musi_care::qt_commandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool status\n"
"\n"
;
  }

  static const char* value(const ::musi_care::qt_commandResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::musi_care::qt_commandResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct qt_commandResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::musi_care::qt_commandResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::musi_care::qt_commandResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MUSI_CARE_MESSAGE_QT_COMMANDRESPONSE_H
