// Generated by gencpp from file musi_care/sound_player_srvResponse.msg
// DO NOT EDIT!


#ifndef MUSI_CARE_MESSAGE_SOUND_PLAYER_SRVRESPONSE_H
#define MUSI_CARE_MESSAGE_SOUND_PLAYER_SRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace musi_care
{
template <class ContainerAllocator>
struct sound_player_srvResponse_
{
  typedef sound_player_srvResponse_<ContainerAllocator> Type;

  sound_player_srvResponse_()
    : track_title()
    , track_elapsed_time(0.0)
    , track_total_time(0.0)
    , status(false)  {
    }
  sound_player_srvResponse_(const ContainerAllocator& _alloc)
    : track_title(_alloc)
    , track_elapsed_time(0.0)
    , track_total_time(0.0)
    , status(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _track_title_type;
  _track_title_type track_title;

   typedef float _track_elapsed_time_type;
  _track_elapsed_time_type track_elapsed_time;

   typedef float _track_total_time_type;
  _track_total_time_type track_total_time;

   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::musi_care::sound_player_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::musi_care::sound_player_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct sound_player_srvResponse_

typedef ::musi_care::sound_player_srvResponse_<std::allocator<void> > sound_player_srvResponse;

typedef boost::shared_ptr< ::musi_care::sound_player_srvResponse > sound_player_srvResponsePtr;
typedef boost::shared_ptr< ::musi_care::sound_player_srvResponse const> sound_player_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::musi_care::sound_player_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::musi_care::sound_player_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::musi_care::sound_player_srvResponse_<ContainerAllocator1> & lhs, const ::musi_care::sound_player_srvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.track_title == rhs.track_title &&
    lhs.track_elapsed_time == rhs.track_elapsed_time &&
    lhs.track_total_time == rhs.track_total_time &&
    lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::musi_care::sound_player_srvResponse_<ContainerAllocator1> & lhs, const ::musi_care::sound_player_srvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace musi_care

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::musi_care::sound_player_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::musi_care::sound_player_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::musi_care::sound_player_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::musi_care::sound_player_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::musi_care::sound_player_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::musi_care::sound_player_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::musi_care::sound_player_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a58a3e4eb14adf57544e531765e60a08";
  }

  static const char* value(const ::musi_care::sound_player_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa58a3e4eb14adf57ULL;
  static const uint64_t static_value2 = 0x544e531765e60a08ULL;
};

template<class ContainerAllocator>
struct DataType< ::musi_care::sound_player_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "musi_care/sound_player_srvResponse";
  }

  static const char* value(const ::musi_care::sound_player_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::musi_care::sound_player_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string track_title\n"
"float32 track_elapsed_time\n"
"float32 track_total_time\n"
"bool status\n"
"\n"
;
  }

  static const char* value(const ::musi_care::sound_player_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::musi_care::sound_player_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.track_title);
      stream.next(m.track_elapsed_time);
      stream.next(m.track_total_time);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sound_player_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::musi_care::sound_player_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::musi_care::sound_player_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "track_title: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.track_title);
    s << indent << "track_elapsed_time: ";
    Printer<float>::stream(s, indent + "  ", v.track_elapsed_time);
    s << indent << "track_total_time: ";
    Printer<float>::stream(s, indent + "  ", v.track_total_time);
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MUSI_CARE_MESSAGE_SOUND_PLAYER_SRVRESPONSE_H
