// Generated by gencpp from file musi_care/sound_player_srvRequest.msg
// DO NOT EDIT!


#ifndef MUSI_CARE_MESSAGE_SOUND_PLAYER_SRVREQUEST_H
#define MUSI_CARE_MESSAGE_SOUND_PLAYER_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace musi_care
{
template <class ContainerAllocator>
struct sound_player_srvRequest_
{
  typedef sound_player_srvRequest_<ContainerAllocator> Type;

  sound_player_srvRequest_()
    : operation()
    , operation_data_1()
    , operation_data_2(0.0)  {
    }
  sound_player_srvRequest_(const ContainerAllocator& _alloc)
    : operation(_alloc)
    , operation_data_1(_alloc)
    , operation_data_2(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _operation_type;
  _operation_type operation;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _operation_data_1_type;
  _operation_data_1_type operation_data_1;

   typedef float _operation_data_2_type;
  _operation_data_2_type operation_data_2;





  typedef boost::shared_ptr< ::musi_care::sound_player_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::musi_care::sound_player_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct sound_player_srvRequest_

typedef ::musi_care::sound_player_srvRequest_<std::allocator<void> > sound_player_srvRequest;

typedef boost::shared_ptr< ::musi_care::sound_player_srvRequest > sound_player_srvRequestPtr;
typedef boost::shared_ptr< ::musi_care::sound_player_srvRequest const> sound_player_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::musi_care::sound_player_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::musi_care::sound_player_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::musi_care::sound_player_srvRequest_<ContainerAllocator1> & lhs, const ::musi_care::sound_player_srvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.operation == rhs.operation &&
    lhs.operation_data_1 == rhs.operation_data_1 &&
    lhs.operation_data_2 == rhs.operation_data_2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::musi_care::sound_player_srvRequest_<ContainerAllocator1> & lhs, const ::musi_care::sound_player_srvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace musi_care

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::musi_care::sound_player_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::musi_care::sound_player_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::musi_care::sound_player_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::musi_care::sound_player_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::musi_care::sound_player_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::musi_care::sound_player_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::musi_care::sound_player_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0c2f2cc2cd7d8db676e682d44ac19b31";
  }

  static const char* value(const ::musi_care::sound_player_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0c2f2cc2cd7d8db6ULL;
  static const uint64_t static_value2 = 0x76e682d44ac19b31ULL;
};

template<class ContainerAllocator>
struct DataType< ::musi_care::sound_player_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "musi_care/sound_player_srvRequest";
  }

  static const char* value(const ::musi_care::sound_player_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::musi_care::sound_player_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string operation\n"
"string operation_data_1\n"
"float32 operation_data_2\n"
;
  }

  static const char* value(const ::musi_care::sound_player_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::musi_care::sound_player_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.operation);
      stream.next(m.operation_data_1);
      stream.next(m.operation_data_2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sound_player_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::musi_care::sound_player_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::musi_care::sound_player_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "operation: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.operation);
    s << indent << "operation_data_1: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.operation_data_1);
    s << indent << "operation_data_2: ";
    Printer<float>::stream(s, indent + "  ", v.operation_data_2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MUSI_CARE_MESSAGE_SOUND_PLAYER_SRVREQUEST_H
