// Generated by gencpp from file qt_emotion_app/suspend.msg
// DO NOT EDIT!


#ifndef QT_EMOTION_APP_MESSAGE_SUSPEND_H
#define QT_EMOTION_APP_MESSAGE_SUSPEND_H

#include <ros/service_traits.h>


#include <qt_emotion_app/suspendRequest.h>
#include <qt_emotion_app/suspendResponse.h>


namespace qt_emotion_app
{

struct suspend
{

typedef suspendRequest Request;
typedef suspendResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct suspend
} // namespace qt_emotion_app


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qt_emotion_app::suspend > {
  static const char* value()
  {
    return "1ec93149d55d1527cff5331cb7a5fe0a";
  }

  static const char* value(const ::qt_emotion_app::suspend&) { return value(); }
};

template<>
struct DataType< ::qt_emotion_app::suspend > {
  static const char* value()
  {
    return "qt_emotion_app/suspend";
  }

  static const char* value(const ::qt_emotion_app::suspend&) { return value(); }
};


// service_traits::MD5Sum< ::qt_emotion_app::suspendRequest> should match
// service_traits::MD5Sum< ::qt_emotion_app::suspend >
template<>
struct MD5Sum< ::qt_emotion_app::suspendRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qt_emotion_app::suspend >::value();
  }
  static const char* value(const ::qt_emotion_app::suspendRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_emotion_app::suspendRequest> should match
// service_traits::DataType< ::qt_emotion_app::suspend >
template<>
struct DataType< ::qt_emotion_app::suspendRequest>
{
  static const char* value()
  {
    return DataType< ::qt_emotion_app::suspend >::value();
  }
  static const char* value(const ::qt_emotion_app::suspendRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qt_emotion_app::suspendResponse> should match
// service_traits::MD5Sum< ::qt_emotion_app::suspend >
template<>
struct MD5Sum< ::qt_emotion_app::suspendResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qt_emotion_app::suspend >::value();
  }
  static const char* value(const ::qt_emotion_app::suspendResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_emotion_app::suspendResponse> should match
// service_traits::DataType< ::qt_emotion_app::suspend >
template<>
struct DataType< ::qt_emotion_app::suspendResponse>
{
  static const char* value()
  {
    return DataType< ::qt_emotion_app::suspend >::value();
  }
  static const char* value(const ::qt_emotion_app::suspendResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QT_EMOTION_APP_MESSAGE_SUSPEND_H
