#!/usr/bin/env python

import cv2

import rospy
from sensor_msgs.msg import Image
from cv_bridge import CvBridge
#from std_msgs.msg import String

bridge = CvBridge()
closer_program = False

def DisplayImage(image):
    print(image.shape)
    cv2.imshow("QT Vision", image)
    key = cv2.waitKey(1)
    if key == 27: #Exit on esc
        cv2.destroyAllWindows()

def ProcessImage(data):
    image = bridge.imgmsg_to_cv2(data, "bgr8")
    DisplayImage(image)

def DisplayImageSteam():
    rospy.init_node('display',anonymous=True)
    rospy.Subscriber("/camera/color/image_raw", Image, ProcessImage)
    rospy.spin() #Keep python running

if __name__ == '__main__':
    try:
        DisplayImageSteam()
    except:
        pass
