#!/usr/bin/env python
import sys
import rospy
from qt_robot_interface.srv import *
from qt_gesture_controller.srv import *
from qt_motors_controller.srv import *

if __name__ == '__main__':
    rospy.init_node('record_gesture')

    gestureRecord = rospy.ServiceProxy('/qt_robot/gesture/record', gesture_record)
    gestureSave = rospy.ServiceProxy('/qt_robot/gesture/save', gesture_save)
    setControlMode = rospy.ServiceProxy('/qt_robot/motors/setControlMode', set_control_mode)
    gesturePlay = rospy.ServiceProxy('/qt_robot/gesture/play', gesture_play)


    try:
        name = "my_gesture"
        parts = ["right_arm"]
        input('Press enter to START recording ...\n')
        res = gestureRecord(parts, True, 0, 0)
        if not res.status:
            rospy.logfatal("Could not start recording gesture '%s' using '%s'." % (name, parts))
        input('Press enter to STOP recording ...\n')
        res = gestureSave(name, "")
        if not res.status:
            rospy.logfatal("Could not save gesture '%s'." % name)
        else:
            rospy.loginfo("Gesture '%s' was recorded." % name)
        res = setControlMode(parts, 1)
        if not res.status:
            rospy.logfatal("Could not set control mode of '%s'." % parts)
        else:
            print("Now playing recorded gesture..")
            gesturePlay(name, 0)

    except KeyboardInterrupt:
        pass

    rospy.loginfo("finsihed!")
