#!/usr/bin/env python

#libraries
from guess_mood import Guess_The_Mood_Game
from fix_song import Fix_The_Song_Game
from clap_beat import Clap_To_Beat_Game
from simon_says_clap import Simon_Says_Clap_Game
from musicare_lib import QTManager
from musicare_lib import StandardLevels
from musicare_lib import Behaviours
from std_msgs.msg import Float64MultiArray
import rospy
import time


#init node
rospy.init_node('Pilot', anonymous=False)
rospy.loginfo("Pilot node launched successfully")


arm_up_right = [20, -59.599998474121094, -40.70000076293945] #motor pos for right arm to be in air
arm_up_left = [-20, -59.599998474121094, -40.70000076293945] #motor pos for right arm to be in air
arms_up = '[["right_arm", "left_arm"], [{}, {}]]'.format(arm_up_right,arm_up_left)

user_id = "123"
game = Guess_The_Mood_Game(user_id)
levels = StandardLevels(game.window, game.window_center, game.pygame, game.music_filepath)
qt_manager = QTManager(levels = levels)
qt_manager.qt_actuate(arms_up)