// Generated by gencpp from file qt_idle_app/suspendRequest.msg
// DO NOT EDIT!


#ifndef QT_IDLE_APP_MESSAGE_SUSPENDREQUEST_H
#define QT_IDLE_APP_MESSAGE_SUSPENDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qt_idle_app
{
template <class ContainerAllocator>
struct suspendRequest_
{
  typedef suspendRequest_<ContainerAllocator> Type;

  suspendRequest_()
    : flag(false)  {
    }
  suspendRequest_(const ContainerAllocator& _alloc)
    : flag(false)  {
  (void)_alloc;
    }



   typedef uint8_t _flag_type;
  _flag_type flag;





  typedef boost::shared_ptr< ::qt_idle_app::suspendRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qt_idle_app::suspendRequest_<ContainerAllocator> const> ConstPtr;

}; // struct suspendRequest_

typedef ::qt_idle_app::suspendRequest_<std::allocator<void> > suspendRequest;

typedef boost::shared_ptr< ::qt_idle_app::suspendRequest > suspendRequestPtr;
typedef boost::shared_ptr< ::qt_idle_app::suspendRequest const> suspendRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qt_idle_app::suspendRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qt_idle_app::suspendRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::qt_idle_app::suspendRequest_<ContainerAllocator1> & lhs, const ::qt_idle_app::suspendRequest_<ContainerAllocator2> & rhs)
{
  return lhs.flag == rhs.flag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::qt_idle_app::suspendRequest_<ContainerAllocator1> & lhs, const ::qt_idle_app::suspendRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace qt_idle_app

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::qt_idle_app::suspendRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qt_idle_app::suspendRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qt_idle_app::suspendRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qt_idle_app::suspendRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qt_idle_app::suspendRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qt_idle_app::suspendRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qt_idle_app::suspendRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "24842bc754e0f5cc982338eca1269251";
  }

  static const char* value(const ::qt_idle_app::suspendRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x24842bc754e0f5ccULL;
  static const uint64_t static_value2 = 0x982338eca1269251ULL;
};

template<class ContainerAllocator>
struct DataType< ::qt_idle_app::suspendRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qt_idle_app/suspendRequest";
  }

  static const char* value(const ::qt_idle_app::suspendRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qt_idle_app::suspendRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"bool flag\n"
;
  }

  static const char* value(const ::qt_idle_app::suspendRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qt_idle_app::suspendRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct suspendRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qt_idle_app::suspendRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qt_idle_app::suspendRequest_<ContainerAllocator>& v)
  {
    s << indent << "flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QT_IDLE_APP_MESSAGE_SUSPENDREQUEST_H
