// Auto-generated. Do not edit!

// (in-package jwaad_test.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class FaceLockOnGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.y_offset = null;
      this.x_offset = null;
    }
    else {
      if (initObj.hasOwnProperty('y_offset')) {
        this.y_offset = initObj.y_offset
      }
      else {
        this.y_offset = 0;
      }
      if (initObj.hasOwnProperty('x_offset')) {
        this.x_offset = initObj.x_offset
      }
      else {
        this.x_offset = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type FaceLockOnGoal
    // Serialize message field [y_offset]
    bufferOffset = _serializer.int16(obj.y_offset, buffer, bufferOffset);
    // Serialize message field [x_offset]
    bufferOffset = _serializer.int16(obj.x_offset, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type FaceLockOnGoal
    let len;
    let data = new FaceLockOnGoal(null);
    // Deserialize message field [y_offset]
    data.y_offset = _deserializer.int16(buffer, bufferOffset);
    // Deserialize message field [x_offset]
    data.x_offset = _deserializer.int16(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'jwaad_test/FaceLockOnGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '0b4343f973d79e4f2bb90d257f10526b';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal definition
    int16 y_offset
    int16 x_offset
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new FaceLockOnGoal(null);
    if (msg.y_offset !== undefined) {
      resolved.y_offset = msg.y_offset;
    }
    else {
      resolved.y_offset = 0
    }

    if (msg.x_offset !== undefined) {
      resolved.x_offset = msg.x_offset;
    }
    else {
      resolved.x_offset = 0
    }

    return resolved;
    }
};

module.exports = FaceLockOnGoal;
