// Auto-generated. Do not edit!

// (in-package jwaad_test.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class FaceLockOnFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.remaining_y_offset = null;
      this.remaining_x_offset = null;
    }
    else {
      if (initObj.hasOwnProperty('remaining_y_offset')) {
        this.remaining_y_offset = initObj.remaining_y_offset
      }
      else {
        this.remaining_y_offset = 0;
      }
      if (initObj.hasOwnProperty('remaining_x_offset')) {
        this.remaining_x_offset = initObj.remaining_x_offset
      }
      else {
        this.remaining_x_offset = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type FaceLockOnFeedback
    // Serialize message field [remaining_y_offset]
    bufferOffset = _serializer.int16(obj.remaining_y_offset, buffer, bufferOffset);
    // Serialize message field [remaining_x_offset]
    bufferOffset = _serializer.int16(obj.remaining_x_offset, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type FaceLockOnFeedback
    let len;
    let data = new FaceLockOnFeedback(null);
    // Deserialize message field [remaining_y_offset]
    data.remaining_y_offset = _deserializer.int16(buffer, bufferOffset);
    // Deserialize message field [remaining_x_offset]
    data.remaining_x_offset = _deserializer.int16(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'jwaad_test/FaceLockOnFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'f85529854f9db9feef1acea870997bcc';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #feedback
    int16 remaining_y_offset
    int16 remaining_x_offset
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new FaceLockOnFeedback(null);
    if (msg.remaining_y_offset !== undefined) {
      resolved.remaining_y_offset = msg.remaining_y_offset;
    }
    else {
      resolved.remaining_y_offset = 0
    }

    if (msg.remaining_x_offset !== undefined) {
      resolved.remaining_x_offset = msg.remaining_x_offset;
    }
    else {
      resolved.remaining_x_offset = 0
    }

    return resolved;
    }
};

module.exports = FaceLockOnFeedback;
